# Generated by Django 4.2.5 on 2023-10-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled_classes',
            field=models.ManyToManyField(blank=True, to='users.class'),
        ),
    ]
