# Generated by Django 4.2.4 on 2023-10-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_completetext_grade_completetext_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlesson',
            name='submitted',
        ),
    ]
