# Generated by Django 4.2.4 on 2023-10-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_textlesson_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completetext',
            name='submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
