# Generated by Django 4.2.4 on 2023-10-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_completetext_submissions_alter_grade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='submissions',
            field=models.IntegerField(default=0),
        ),
    ]
