# Generated by Django 4.2.4 on 2023-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_grade_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='semester',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='textlesson',
            name='semester',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
